// <auto-generated />
using FitTrack.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FitTrack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430154828_AddAdminPaymentAccounts")]
    partial class AddAdminPaymentAccounts
    {
    }
}
